# F-Test ANOVA

In [17]:
import math
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.linear_model import LinearRegression

np.random.seed(seed=42)

%matplotlib inline

In [54]:
#@title Parâmetros da Simulação

n_samples = 42 #@param
n_class = 6 #@param
n_informative = 4 #@param

ci = 0.95 #@param
alpha = 1 - ci

k = n_class - 1
n_comp = (k * (k - 1)) / 2 # de comparações

df_t = n_samples - 1
df_g = n_class - 1
df_e = df_t - df_g

alpha_star = alpha / n_comp

In [55]:
X, y = datasets.make_regression(n_samples=42, n_features=n_class, n_informative=n_informative)

X.shape, y.shape

((42, 6), (42,))

In [56]:
SST = sum(pow(X - y.mean(), 2))
SSG = sum(n_samples * (X.mean(axis=0) - y.mean()))
SSE = SST - SSG

SSE

array([11773.71379423, 10764.90105577, 10590.0805677 , 11032.02189124,
       11227.95107188, 11269.74650235])

In [57]:
MSG = SSG / df_g
MSE = SSE / df_e

In [58]:
F = MSG / MSE
F = abs(F)
F

array([3.00663442, 3.28839559, 3.34268025, 3.20877292, 3.15277943,
       3.1410869 ])

In [60]:
stats.f.pdf(F, df_g, df_e)

array([0.0335123 , 0.02193391, 0.02022189, 0.02471689, 0.02688738,
       0.02736458])